FROM golang:alpine
WORKDIR /app
COPY ./go-app/go.mod /app
COPY ./go-app/main.go /app
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./out/app ./main.go
ENTRYPOINT [ "./out/app" ] 